// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	localtest: string;
	fixedURL: string;
	debug: boolean;
	assign: boolean;
}
